# Generated by Django 4.2.7 on 2026-02-16 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0015_alter_chauffeur_super_chauffeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('danger', 'Urgent'), ('success', 'Succès')], default='info', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Lu par')),
            ],
            options={
                'verbose_name': 'Notification Admin',
                'verbose_name_plural': 'Notifications Admin',
                'ordering': ['-date_creation'],
            },
        ),
    ]
