# Generated by Django 4.2.7 on 2026-01-29 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_chauffeur_super_chauffeur'),
        ('chauffeurs_mobile', '0002_delete_reservationagent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification mobile', 'verbose_name_plural': 'Notifications mobiles'},
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_mobile', to='gestion.chauffeur'),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='type_notification',
            field=models.CharField(choices=[('reservation', 'Nouvelle réservation'), ('annulation', 'Annulation de réservation'), ('info', 'Information'), ('alerte', 'Alerte'), ('super_reservation', 'Réservation par Super Chauffeur'), ('super_annulation', 'Annulation par Super Chauffeur')], max_length=20),
        ),
    ]
