# Generated by Django 4.2.7 on 2026-02-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_chauffeur_super_chauffeur'),
        ('chauffeurs_mobile', '0003_alter_mobilenotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenotification',
            name='date_transport',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='groupe_notification',
            field=models.CharField(blank=True, help_text='Clé pour grouper les notifications par heure', max_length=100),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='heure_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='gestion.heuretransport'),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='type_transport',
            field=models.CharField(blank=True, choices=[('ramassage', 'Ramassage'), ('depart', 'Départ'), ('', 'Non spécifié')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='type_notification',
            field=models.CharField(choices=[('reservation', 'Nouvelle réservation'), ('annulation', 'Annulation de réservation'), ('info', 'Information'), ('alerte', 'Alerte'), ('super_reservation', 'Réservation par Super Chauffeur'), ('super_annulation', 'Annulation par Super Chauffeur'), ('agent_selection', 'Agent à transporter'), ('transport_confirmation', 'Confirmation transport')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='mobilenotification',
            index=models.Index(fields=['groupe_notification', '-created_at'], name='chauffeurs__groupe__4f3e85_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilenotification',
            index=models.Index(fields=['chauffeur', 'vue', 'created_at'], name='chauffeurs__chauffe_d177e7_idx'),
        ),
    ]
