# Generated by Django 4.2.7 on 2026-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs_mobile', '0004_mobilenotification_date_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenotification',
            name='agents_list',
            field=models.JSONField(blank=True, default=list, help_text='Liste des agents dans une notification groupée'),
        ),
    ]
