# Generated by Django 4.2.7 on 2026-02-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs_mobile', '0005_mobilenotification_agents_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenotification',
            name='agents_list',
        ),
    ]
